bcgov/parks-reso-admin

- .github/workflows/deploy-dev.yaml
- .github/workflows/deploy-test.yaml
- terraform/terragrunt.hcl
for infra rebuild using the new TFC workspaces to isolate deploy configurations
> temporary modification: skip deploy, and run terragrunt destroy 

- .github/pull_request_template.md
- .prettierrc
- package.json
- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/breadcrumb/breadcrumb.component.html
- src/app/breadcrumb/breadcrumb.component.ts
- src/app/guards/auth.guard.spec.ts
- src/app/guards/auth.guard.ts
- src/app/not-authorized/not-authorized.component.html
- src/app/not-authorized/not-authorized.component.scss
- src/app/not-authorized/not-authorized.component.ts
BRS-163
https://bcparksdigital.atlassian.net/browse/BRS-163
Add auth guard to prevent unauthorized navigations
> BRS-163 Add auth guard

- src/app/facility/facility-details/facility-details.component.html
- src/app/facility/facility-details/facility-details.component.ts
- src/app/shared/utils/pass-utils.ts
BRS-149
https://bcparksdigital.atlassian.net/browse/BRS-149
Add `Copy Emails` button to copy unique emails to clipboard
> BRS-149 Export email button

- src/app/facility-form/facility-form.component.html
- src/app/facility-form/facility-form.component.ts
- src/app/facility/facility-details/facility-details.component.html
- src/app/facility/facility-details/facility-details.component.ts
- src/app/models/facility.ts
- src/env.js
- src/env.js.template
BRS-148
https://bcparksdigital.atlassian.net/browse/BRS-148
Adds edit fields to the admin for facility `bookingOpeningHour` and `bookingDaysAhead`.
Depends on https://github.com/bcgov/parks-reso-api/pull/33 on the API side.
> BRS-148: add booking window details to facility admin

- angular.json
- src/index.html
- src/snowplow.js
BRS-147
https://bcparksdigital.atlassian.net/browse/BRS-147
Set up site metrics for Parking Pass site.
> BRS-147: Moving snowplow to its own file

- src/app/services/api.service.ts
BRS-211
https://bcparksdigital.atlassian.net/browse/BRS-211
Front-end changes linked with https://github.com/bcgov/parks-reso-api/pull/37
> BRS-211: Duplicated Park in DUP was created when editing park details.

- src/app/facility-form/facility-form.component.html
- src/app/facility-form/facility-form.component.ts
- src/app/facility/facility-details/facility-details.component.html
- src/app/facility/facility-details/facility-details.component.ts
- src/app/models/facility.ts
- src/app/shared/utils/utils.ts
BRS-148
https://bcparksdigital.atlassian.net/browse/BRS-148
Switch time to am/pm, days dropdown as the numeric fields were too confusing.
> BRS-148: update booking window form UX

- .github/workflows/deploy-dev.yaml
- .github/workflows/deploy-prod.yaml
- .github/workflows/deploy-test.yaml
BRS-219
https://bcparksdigital.atlassian.net/browse/BRS-219
Admin version of https://github.com/bcgov/parks-reso-public/pull/84
> BRS-219: upload to s3 before updating cloudfront distribution

- src/app/models/park.ts
- src/app/park-form/park-form.component.html
- src/app/park-form/park-form.component.ts
- src/app/park/park-details/park-details.component.html
BRS-248
https://bcparksdigital.atlassian.net/browse/BRS-248
Add mapLink to admin interface. Requires https://github.com/bcgov/parks-reso-api/pull/44
> BRS-248: add mapLink to admin interface

- .github/workflows/deploy-prod.yaml
- angular.json
- terraform/prod/terragrunt.hcl
- terraform/src/cloudfront.tf
- terraform/src/variables.tf
BRS-247
https://bcparksdigital.atlassian.net/browse/BRS-247
Add vanity URL & set path to /dayuse/
> BRS-247: add vanity domain config & set path to /dayuse

- .github/workflows/deploy-dev.yaml
- .github/workflows/deploy-prod.yaml
- .github/workflows/deploy-test.yaml
- package.json
BRS-247
https://bcparksdigital.atlassian.net/browse/BRS-247
Missed the dayuse prefix in a few spots
> BRS-247: fix dayuse path

- src/app/services/config.service.ts
BRS-247
https://bcparksdigital.atlassian.net/browse/BRS-247
Without a leading slash it resolves to /dayuse/api/config
> BRS-247: fix api path in config service

- package.json
- src/app/park-form/park-form.component.html
BRS-247
https://bcparksdigital.atlassian.net/browse/BRS-247
TinyMCE also needs a /dayuse prefix.
> BRS-247: fix tinymce load path

- angular.json
> NOBUG: fixing snowplow

- package.json
- yarn.lock
Fixing issues with yarn start.
> NOBUG: Fixing issues with yarn start

- src/app/facility/facility-details/facility-details.component.html
- src/app/facility/facility-details/facility-details.component.ts
BRS-274
https://bcparksdigital.atlassian.net/browse/BRS-274
Adding capacity summary when filtering by date for get pass.
> BRS-274: Adding capacity summary when filtering by date for get pass

- package.json
- src/app/facility/facility-details/facility-details.component.html
- src/app/facility/facility-details/facility-details.component.ts
- src/app/facility/facility-resolver.service.ts
- src/app/facility/facility.module.ts
- src/app/passes/pass-list/pass-list.component.html
- src/app/passes/pass-list/pass-list.component.ts
- src/app/services/pass.service.ts
- src/app/shared/components/search-widget/search-widget-object.ts
- src/app/shared/components/search-widget/search-widget.component.ts
- src/tsconfig.app.json
- src/tsconfig.spec.json
- yarn.lock
BRS-310
https://bcparksdigital.atlassian.net/browse/BRS-310
- Fixed pass search filters.
- Fixed AM, PM and DAY filter.
- Fixed show more button.
- Removed pagination temporarily.
- Removed result count.
> BRS-310: Fixing various issues with pass table

- src/app/passes/pass-list/pass-list.component.html
BRS-355
https://bcparksdigital.atlassian.net/browse/BRS-355
Hide show more button if table has 0 items.
> BRS-355: Hide show more button if table has 0 items

- src/app/facility/facility-details/facility-details.component.ts
BRS-311
https://bcparksdigital.atlassian.net/browse/BRS-311
This is the front end adjustments to grab a CSV from the back-end.
> BRS-311: Update open CSV to S3 generated endpoint.

- src/app/home/home.component.html
NOBUG
Updates text on the metrics card component.
> NOBUG: Change text on metrics card.

- src/app/services/keycloak.service.ts
BRS-597
https://bcparksdigital.atlassian.net/browse/BRS-597
This changes the back-end to look at the parks-pass client based roles.  All environments have oidc changes ready.
> BRS-597: client based role approach

- src/app/services/api.service.ts
- yarn.lock
BRS-598
https://bcparksdigital.atlassian.net/browse/BRS-598
BRS-598: Updating header bar to use full name instead of idir display name.
> BRS-598: Updating header bar to use full name instead of idir display name

- src/app/services/keycloak.service.ts
BRS-657
https://bcparksdigital.atlassian.net/browse/BRS-657
Disables iframe checking, adds console logs to verify in environments.
> BRS-657: DUP Admin TEST - Losing permissions after a few seconds

- package.json
- yarn.lock
BRS-661
https://bcparksdigital.atlassian.net/browse/BRS-661
Removed unused packages.
> BRS-661: removed unused packages

- src/app/models/park.ts
- src/app/park-form/park-form.component.html
- src/app/park-form/park-form.component.ts
- src/app/services/keycloak.service.ts
- src/app/services/park.service.ts
- src/env.js
BRS-299
https://bcparksdigital.atlassian.net/browse/BRS-299
Switches to use client-based roles, instead of realm based.
> BRS-299: Roles use client-based roles, instead of realm based roles.

- src/app/app-routing.module.ts
- src/app/app.component.html
- src/app/app.component.ts
- src/app/app.module.ts
- src/app/breadcrumb/breadcrumb.component.html
- src/app/breadcrumb/breadcrumb.component.ts
- src/app/guards/auth.guard.spec.ts
- src/app/guards/auth.guard.ts
- src/app/header/header.component.html
- src/app/header/header.component.ts
- src/app/login/login.component.html
- src/app/login/login.component.scss
- src/app/login/login.component.ts
- src/app/not-authorized/not-authorized.component.html
- src/app/not-authorized/not-authorized.component.scss
- src/app/not-authorized/not-authorized.component.ts
- src/app/services/keycloak.service.spec.ts
- src/app/services/keycloak.service.ts
- src/app/toggle-button/toggle-button.component.html
- src/app/toggle-button/toggle-button.component.ts
- src/assets/styles/layout/no-sidebar.scss
- src/assets/styles/themes/default.scss
BRS-647
https://bcparksdigital.atlassian.net/browse/BRS-647
Implemented a custom Keycloak login page as part of the Day Use Pass admin system.
> ﻿BRS-647: DUP login page

- src/app/login/login.component.ts
BRS-647
https://bcparksdigital.atlassian.net/browse/BRS-647
Fixed an error that only occurred when running prod builds.  
A ticket has also been created to add check to future pull requests: https://bcparksdigital.atlassian.net/browse/BRS-689
> BRS-647: Fixed error when running `ng build --prod`

- terraform/src/cloudfront.tf
BRS-686
https://bcparksdigital.atlassian.net/browse/BRS-686
BRS-686: Enable Blacklist for restricted countries.
> BRS-686: Enable Blacklist for restricted countries.

- src/app/facility/facility-details/facility-details.component.ts
- src/app/passes/pass-list/pass-list.component.ts
NOBUG
Pass display in facility details/edit was incorrectly converting `pass.date` to `JSDate()`, causing syntactical errors.
> NOBUG - incorrect pass date conversion to JSDate resolved

- src/app/facility/facility-details/facility-details.component.ts
- src/app/facility/facility-resolver.service.ts
- src/app/park/park.module.ts
- src/app/passes/pass-list/pass-table-row/pass-table-row.component.ts
- src/app/services/api.service.ts
- src/app/services/reservation.service.ts
BRS-594
https://bcparksdigital.atlassian.net/browse/BRS-594
Updating capacity bar to use new reservation obj.
> BRS-594: Updating capacity bar to use new reservation obj.

- src/app/facility/facility-details/facility-details.component.ts
BRS-745
https://bcparksdigital.atlassian.net/browse/BRS-745
Updated the capacity bar to get the capacity from the reservation capacities `baseCapacity + capacityModifier` instead of from the facility default capacity.
> BRS-745: Capacity bar should use reservation capacity, not facility capacity

- src/app/facility/facility-details/facility-details.component.ts
BRS-745
https://bcparksdigital.atlassian.net/browse/BRS-745
Fixed a bug reported by QA that was impacting days with no reservation object for the facility (i.e. days with no bookings)
The capacity bar was showing the capacity from the most recent date you searched for that had actually had a booking, instead of showing the facility capacity.
> BRS-745: Fixed a bug impacting days with no bookings

- src/app/facility/facility-details/facility-details.component.html
> NOBUG: fixing mod label bug

- src/app/facility-form/facility-form.component.ts
- src/app/facility-form/modifier-form/modifier-form.component.ts
- src/app/facility/facility-details/facility-details.component.ts
- src/app/facility/facility-edit/facility-edit.component.html
- src/app/facility/facility-resolver.service.ts
NOBUG
Pass table should update after editing facility.
> NOBUG: QOL changes.

- src/app/models/facility.ts
BRS-768
https://bcparksdigital.atlassian.net/browse/BRS-768
Minor update to facility model to accompany the changes in https://github.com/bcgov/parks-reso-api/pull/173.
> BRS-768 pt. 1: BE changes to allow for weekend bookings

- src/app/facility-form/modifier-form/modifier-form.component.html
- src/app/facility-form/modifier-form/modifier-form.component.scss
- src/app/facility-form/modifier-form/modifier-form.component.ts
BRS-722
https://bcparksdigital.atlassian.net/browse/BRS-722
Modifier UI Updates
> BRS-722: Modifier UI Updates

- src/app/facility-form/facility-form.component.ts
BRS-747
https://bcparksdigital.atlassian.net/browse/BRS-747
Refresh reservations bar after facility edit.
> BRS-747: Refresh reservations bar after facility edit

- src/app/parks/parks.component.html
BRS-685
https://bcparksdigital.atlassian.net/browse/BRS-685
Removing add park button.
> BRS-685: Removing add park button

- src/app/facilities/facilities.module.ts
- src/app/facility-form/facility-form.component.html
- src/app/facility-form/facility-form.component.scss
- src/app/facility-form/facility-form.component.ts
- src/app/shared/utils/constants.ts
BRS-787
https://bcparksdigital.atlassian.net/browse/BRS-787
Admin portal portion of FE changes to incorporate weekday-specific booking. Requires the code changes and migrations included in BRS-787.
> BRS-787 weekday specific bookings admin FE changes

- src/app/app-routing.module.ts
- src/app/guards/auth.guard.ts
- src/app/home/home.component.html
- src/app/home/home.component.ts
- src/app/services/keycloak.service.ts
- src/app/sidebar/sidebar.component.html
- src/app/sidebar/sidebar.component.ts
BRS-795
https://bcparksdigital.atlassian.net/browse/BRS-795
This ticket is to limit the full pass data export (BRS-592) to only allow sysadmin role to do it. This is to prevent any pass data being shared with the wrong person.
> BRS-795: Full data export in DUP should be limited to sysadmin role

- src/app/facility-form/facility-form.component.html
- src/app/facility-form/facility-form.component.scss
BRS-763
https://bcparksdigital.atlassian.net/browse/BRS-763
Made minor adjustments according to the following
Font size and vertical alignment for toggle
https://bcparksdigital.atlassian.net/browse/BRS-763?focusedCommentId=12457
Remove shading according to screenshot
https://github.com/bcgov/parks-reso-admin/pull/122#pullrequestreview-1080920944
> BRS-763: Minor adjustments to UI

- src/app/facility-form/facility-form.component.html
- src/app/facility-form/facility-form.component.ts
BRS-801, BRS-802, BRS-803, BRS-804
https://bcparksdigital.atlassian.net/browse/BRS-801
https://bcparksdigital.atlassian.net/browse/BRS-802
https://bcparksdigital.atlassian.net/browse/BRS-803
https://bcparksdigital.atlassian.net/browse/BRS-804
UI updates for weekday bookings
> BRS-801 et al - weekday booking UI changes

- src/app/facility-form/facility-form.component.ts
BRS-780
https://bcparksdigital.atlassian.net/browse/BRS-780
This fixes the opening time payload by setting the form to show the default hour and am/pm if it wasn't selected.
> BRS-780: Issue when no value is set for the "Booking opening time"

- angular.json
- src/app/facilities/facilities-routes.ts
- src/app/park/park-details/park-details.component.html
- src/app/park/park-details/park-details.component.ts
- src/app/park/park-routes.ts
BRS-726
https://bcparksdigital.atlassian.net/browse/BRS-726
Removes the routes and buttons for add facility when not a sysadmin (and changes the old markup to be a div, not an input)
> BRS-726: remove "add facility" button for non-sysadmin users

- src/app/park-form/park-form.component.html
- src/app/park-form/park-form.component.ts
- src/app/park/park-details/park-details.component.html
- src/app/parks/park-list/park-table-row/park-table-row.component.ts
BRS-797
https://bcparksdigital.atlassian.net/browse/BRS-797
Minor text change. Wording 'open/closed' changed to 'passes required/not required' at park level.
> BRS-797 changing open/closed wording to passes required/not required at park level

- src/app/metrics/metrics.component.html
- src/app/metrics/metrics.component.ts
BRS-592
https://bcparksdigital.atlassian.net/browse/BRS-592
This adds a button for kicking off the export all pass jobs.  Requires PR #183 in API.
> BRS-592: Adding button for kicking off the export all pass jobs.

- src/app/parks-management/facility-details/passes-filter/passes-filter-fields/passes-filter-fields.component.html
- src/app/parks-management/facility-edit/facility-edit-form/facility-edit-form-details/facility-edit-form-details.component.html
- src/app/parks-management/facility-edit/facility-edit-form/facility-edit-form-pass-requirements/facility-edit-form-pass-requirements.component.html
- src/app/parks-management/facility-edit/facility-edit-form/facility-edit-form-publishing-details/facility-edit-form-publishing-details.component.html
- src/app/parks-management/modifiers-form/modifiers-form.component.html
- src/app/parks-management/modifiers-list/modifiers-list.component.ts
- src/app/parks-management/park-edit-form/park-edit-form.component.html
- src/app/parks-management/park-edit-form/park-edit-form.component.ts
- src/app/shared/components/ds-forms/checkbox/checkbox.component.html
- src/app/shared/components/ds-forms/multiselect/multiselect.component.html
- src/app/shared/components/ds-forms/text-input/text-input.component.html
- src/app/shared/components/ds-forms/wysiwyg-input/wysiwyg-input.component.html
NOBUG
Changes to improve WCAG compliance.
> NOBUG: Improving accessibility

- src/app/parks-management/facility-edit/facility-edit-form/facility-edit-form-pass-requirements/facility-edit-form-pass-requirements.component.html
- src/app/parks-management/facility-edit/facility-edit-form/facility-edit-form-pass-requirements/facility-edit-form-pass-requirements.component.ts
- src/app/parks-management/facility-edit/facility-edit-form/facility-edit-form.component.html
- src/app/parks-management/facility-edit/facility-edit-form/facility-edit-form.component.spec.ts
- src/app/parks-management/facility-edit/facility-edit-form/facility-edit-form.component.ts
- src/app/parks-management/park-edit-form/park-edit-form.component.html
- src/app/parks-management/park-edit-form/park-edit-form.component.spec.ts
- src/app/parks-management/park-edit-form/park-edit-form.component.ts
- src/app/shared/components/modal/modal.component.html
- src/app/shared/components/modal/modal.component.ts
- src/app/shared/utils/constants.ts
- src/app/shared/utils/utils.ts
BRS-910
https://bcparksdigital.atlassian.net/browse/BRS-910
Adding confirmation modals when submitting changes in park/facility edit
> BRS-910 adding confirmation modals to park/facility edit

- src/app/parks-management/park-details/park-details.component.html
- src/app/parks-management/park-details/park-details.component.spec.ts
- src/app/parks-management/park-details/park-details.component.ts
- src/app/services/keycloak.service.ts
- src/app/services/sidebar.service.ts
- src/app/shared/components/fancy-header/fancy-header.component.html
BRS-913
https://bcparksdigital.atlassian.net/browse/BRS-913
Restricting access to add facility.
> BRS-913: Restricting access to add facility

- yarn.lock
This is applies some security updates to the yarn.lock
> NOBUG: Security updates.

- src/app/parks-management/facility-edit/facility-edit-form/facility-edit-form.component.ts
BRS-914
https://bcparksdigital.atlassian.net/browse/BRS-914
Fixing undefined visibility default.
> BRS-914: fixing undefined visibility default

- src/app/parks-management/facility-edit/facility-edit-form/facility-edit-form.component.ts
- src/app/parks-management/park-edit-form/park-edit-form.component.ts
- src/app/services/facility.service.ts
- src/app/services/keycloak.service.ts
NOBUG
Added to keycloak service.
Fixed moved where facility list is refreshed.
> NOBUG: Clean up

- src/app/parks-management/park-edit-form/park-edit-form.component.ts
BRS-910
https://bcparksdigital.atlassian.net/browse/BRS-910
> BRS-910-2: Park edit modal shows correct park status

- src/app/parks-management/facility-edit/facility-edit-form/facility-edit-form.component.html
- src/app/parks-management/facility-edit/facility-edit-form/facility-edit-form.component.ts
- src/app/parks-management/park-edit-form/park-edit-form.component.html
- src/app/parks-management/park-edit-form/park-edit-form.component.ts
BRS-909
https://bcparksdigital.atlassian.net/browse/BRS-909
> BRS-909: Adding cancel button to park/facility edit

- src/app/parks-management/facility-details/passes-utility-buttons/passes-utility-buttons.component.html
- src/app/parks-management/facility-details/passes-utility-buttons/passes-utility-buttons.component.spec.ts
- src/app/parks-management/facility-details/passes-utility-buttons/passes-utility-buttons.component.ts
BRS-912
https://bcparksdigital.atlassian.net/browse/BRS-912
Remove export button when not sysadmin.
> BRS-912: Remove export button when not sysadmin.

- src/app/app-routing.module.ts
- src/app/metrics/metrics-routing.module.ts
- src/app/metrics/metrics.component.html
- src/app/metrics/metrics.component.scss
- src/app/metrics/metrics.component.spec.ts
- src/app/metrics/metrics.component.ts
- src/app/metrics/metrics.module.ts
- src/app/resolvers/metrics.resolver.ts
- src/app/services/metrics.service.ts
- src/app/shared/utils/constants.ts
BRS-893
https://bcparksdigital.atlassian.net/browse/BRS-893
Metrics page added to DUP-angular14, updated services
> BRS-893: Metrics page added

- src/app/services/modifier.service.ts
BRS-921
https://bcparksdigital.atlassian.net/browse/BRS-921
Fixing issues with modifier changes not updating UI.
> BRS-921: Fixing issues with modifier changes not updating UI

- src/app/services/keycloak.service.ts
- src/app/services/sidebar.service.ts
BRS-933
https://bcparksdigital.atlassian.net/browse/BRS-933
Removing metrics from non-sysadmin users.
> BRS-933: removing metrics from non-sysadmin users

- src/app/parks-management/facility-edit/facility-edit.component.ts
- src/app/services/modifier.service.ts
- src/app/shared/utils/utils.ts
BRS-921
https://bcparksdigital.atlassian.net/browse/BRS-921
Fixing TZ issue with modifiers list fetch.
> BRS-921: Fixing TZ issue with modifiers list fetch

- src/app/app-routing.module.ts
BRS-925
https://bcparksdigital.atlassian.net/browse/BRS-925
[Angular's scrollPostionRestoration](https://angular.io/api/router/InMemoryScrollingOptions#scrollPositionRestoration)
> BRS-925 scroll position restoration

- src/app/parks-management/facility-edit/facility-edit.component.html
BRS-926
https://bcparksdigital.atlassian.net/browse/BRS-926
Removing back button on add-facility.
> BRS-926: Removing back button on add-facility

- src/app/home/home.component.ts
BRS-935
https://bcparksdigital.atlassian.net/browse/BRS-935
Re-adding metrics card.
> BRS-935: Re-adding metrics card

- src/app/parks-management/facility-edit/facility-edit-form/facility-edit-form-details/facility-edit-form-details.component.html
- src/app/parks-management/facility-edit/facility-edit-form/facility-edit-form.component.ts
- src/app/shared/components/ds-forms/ds-forms.module.ts
- src/app/shared/components/ds-forms/timepicker/timepicker.component.html
- src/app/shared/components/ds-forms/timepicker/timepicker.component.ts
BRS-928
https://bcparksdigital.atlassian.net/browse/BRS-928
Changing timepicker package.
> BRS-928: Changing timepicker package

- src/app/shared/components/ds-forms/timepicker/timepicker.component.scss
BRS-928
https://bcparksdigital.atlassian.net/browse/BRS-928
Override timepicker CSS.
> BRS-928: Override timepicker CSS

- src/app/parks-management/facility-edit/facility-edit-form/facility-edit-form-details/facility-edit-form-details.component.html
- src/app/parks-management/facility-edit/facility-edit-form/facility-edit-form-pass-requirements/facility-edit-form-pass-requirements.component.html
- src/app/parks-management/facility-edit/facility-edit.component.html
BRS-927, BRS-929, BRS-930
https://bcparksdigital.atlassian.net/browse/BRS-927
https://bcparksdigital.atlassian.net/browse/BRS-929
https://bcparksdigital.atlassian.net/browse/BRS-930
Facility edit visual changes.
> BRS-927, BRS-929, BRS-930: Facility edit visual changes

- src/app/parks-management/facility-edit/facility-edit-form/facility-edit-form-pass-requirements/facility-edit-form-pass-requirements.component.html
- src/app/shared/components/ds-forms/base-input/base-input.component.ts
- src/app/shared/components/ds-forms/wysiwyg-input/wysiwyg-input.component.html
- src/app/shared/components/ds-forms/wysiwyg-input/wysiwyg-input.component.ts
BRS-929
https://bcparksdigital.atlassian.net/browse/BRS-929
Adding extra text to facility edit.
> BRS-929: Adding extra text to facility edit

- src/app/app-routing.module.ts
- src/app/shared/components/sidebar/sidebar.component.html
BRS-923
https://bcparksdigital.atlassian.net/browse/BRS-923
Adding icons to sidebar.
> BRS-923: Adding icons to sidebar

- src/app/header/header.component.html
BRS-923
https://bcparksdigital.atlassian.net/browse/BRS-923
Adding icons to mobile menu.
> BRS-923: Adding icons to mobile menu

- src/app/shared/components/breadcrumb/breadcrumb.component.scss
BRS-938
https://bcparksdigital.atlassian.net/browse/BRS-938
Removing set height from breadcrumb css so height is adapted to length of breadcrumb.
> BRS-938: Breadcrumb padding

- README.md
- src/app/app.module.ts
- src/app/services/auto-fetch.service.ts
- src/app/services/config.service.spec.ts
- src/app/services/config.service.ts
- src/app/services/facility.service.spec.ts
- src/app/services/facility.service.ts
- src/app/services/form.service.spec.ts
- src/app/services/form.service.ts
- src/app/services/keycloak.service.ts
- src/app/services/loading.service.spec.ts
- src/app/services/loading.service.ts
- src/app/services/logger.service.spec.ts
- src/app/services/logger.service.ts
- src/app/services/metric.service.spec.ts
- src/app/services/metric.service.ts
- src/app/services/modifier.service.spec.ts
- src/app/services/modifier.service.ts
- src/app/services/park.service.spec.ts
- src/app/services/park.service.ts
- src/app/services/pass.service.spec.ts
- src/app/services/pass.service.ts
- src/app/services/reservation.service.spec.ts
- src/app/services/reservation.service.ts
- src/app/shared/components/infinite-loading-bar/infinite-loading-bar.component.spec.ts
- src/app/shared/components/table/table.component.spec.ts
- src/app/shared/components/text-to-loading-spinner/text-to-loading-spinner.component.spec.ts
- src/env.js
- src/env.js.template
BRS-948
https://bcparksdigital.atlassian.net/browse/BRS-948
This improves the logging facility in the front end.  Default is debug on localhost and can be overridden in 2 ways: Via api config service, or through the js console: `__env.logLevel=X` where `X` is a number from 0-6
`
export enum LogLevel {
All = 0,
Debug = 1,
Info = 2,
Warn = 3,
Error = 4,
Fatal = 5,
Off = 6
}
`
> BRS-948: Improve Logging in DUP front-end admin.

- src/app/parks-management/facility-edit/facility-edit-form/facility-edit-form-details/facility-edit-form-details.component.html
- src/app/shared/components/ds-forms/timepicker/timepicker.component.html
- src/app/shared/components/ds-forms/timepicker/timepicker.component.ts
BRS-942
https://bcparksdigital.atlassian.net/browse/BRS-942
See ticket comments for rationale.
> BRS-942: removing ambiguous timepicker invalid state

- angular.json
- karma.conf.js
This is adds code coverage report to the cli.
> NOBUG: Adding CC reporting to cli.

- src/app/parks-management/modifiers-list/modifiers-list.component.html
- src/app/parks-management/modifiers-list/modifiers-list.component.ts
BRS-931
https://bcparksdigital.atlassian.net/browse/BRS-931
Remove table when empty, display new empty table text
> BRS-931: Remove table when empty, display new empty table text

- src/app/shared/components/ds-forms/text-area/text-area.component.spec.ts
- src/app/shared/components/ds-forms/text-area/text-area.component.ts
NOBUG
Achieving 💯 % test coverage for `text-area` input (`ds-forms`, unused in DUP admin).
> NOBUG: coverage UTs for text-area input

- src/app/shared/components/ds-forms/base-input/base-input.component.spec.ts
- src/app/shared/components/ds-forms/text-input/text-input.component.spec.ts
NOBUG
Adds 💯 % coverage for `base-input` and `text-input` shared components (`ds-forms`);
> NOBUG: UTs for base-input and text-input components

- src/env.js
- src/env.js.template
BRS-861
https://bcparksdigital.atlassian.net/browse/BRS-861
This moves our OIDC from KC Silver => KC Gold.  Must be done in conjunction with
> BRS-861: Investigate & migrate  to keycloak gold

- src/assets/styles/base/base.scss
BRS-924
https://bcparksdigital.atlassian.net/browse/BRS-924
Making confirmation modal text wrap.
> BRS-924: making confirmation modal text wrap

- src/app/shared/components/ds-forms/base-form/base-form.component.spec.ts
- src/app/shared/components/ds-forms/multiselect/multiselect.component.spec.ts
BRS-965
Getting `base-form` component to 💯 % coverage.
> BRS-965-2: UTs for base-form

- src/app/services/keycloak.service.ts
BRS-975
https://bcparksdigital.atlassian.net/browse/BRS-975
This hides the welcome message from the title bar for BCSC.
> BRS-975: Hide welcome message when BCSC.

- src/app/parks-management/park-details/park-details.component.scss
BRS-937
https://bcparksdigital.atlassian.net/browse/BRS-937
Fixing link wrap on park details.
> BRS-937: Fixing link wrap on park details.

- src/app/header/header.component.spec.ts
- src/app/home/home.component.spec.ts
- src/app/parks-management/facility-details/facility-details.component.spec.ts
- src/app/parks-management/facility-details/passes-filter/passes-filter.component.spec.ts
- src/app/parks-management/facility-details/passes-list/passes-list.component.spec.ts
- src/app/parks-management/facility-details/passes-list/passes-list.component.ts
- src/app/shared/utils/mock-data.ts
BRS-965
Includes improved coverage for `home.component`, `header.component`, `facility-details.component`, ` passes-filter.component`, `passes-list.component.`
Also includes a new file, `mock-data.ts` to store constants that can be used in tests.
Currently at 48.4% coverage.
> BRS-965-3: UTs for facility details, passes, more

- src/app/parks-management/facility-details/passes-utility-buttons/passes-utility-buttons.component.spec.ts
- src/app/parks-management/facility-edit/facility-edit-form/facility-edit-form-pass-requirements/facility-edit-form-pass-requirements.component.spec.ts
- src/app/parks-management/facility-edit/facility-edit-form/facility-edit-form-pass-requirements/facility-edit-form-pass-requirements.component.ts
- src/app/parks-management/facility-edit/facility-edit-form/facility-edit-form.component.spec.ts
- src/app/parks-management/facility-edit/facility-edit-form/facility-edit-form.component.ts
- src/app/parks-management/facility-edit/facility-edit.component.spec.ts
- src/app/shared/utils/mock-data.ts
BRS-965
Adding UTs for `facility-edit` components. Coverage now at 55%.
> BRS-965-4: facility-edit components

- src/app/shared/components/ds-forms/base-form/base-form.component.spec.ts
BRS-965
Race condition in `base-form`, possibly due to https://github.com/angular/angular/issues/22556. Will remove this test if we continue to get inconsistent test failures.
> BRS-965: race condtion in base-form

- src/app/parks-management/modifiers-form/modifiers-form.component.spec.ts
- src/app/parks-management/modifiers-list/modifiers-list.component.spec.ts
- src/app/parks-management/park-details/park-details.component.spec.ts
- src/app/parks-management/park-edit-form/park-edit-form.component.spec.ts
- src/app/parks-management/park-edit-form/park-edit-form.component.ts
- src/app/parks-management/parks-list/parks-list.component.spec.ts
- src/app/shared/utils/mock-data.ts
BRS-965
Improving coverage for parks list/details/edit/add. Coverage at 61%.
> BRS-965-5: park display components

- src/app/shared/components/modal/modal.component.spec.ts
- src/app/shared/components/nav-card/nav-card.component.spec.ts
- src/app/shared/components/select/select.component.spec.ts
- src/app/shared/components/sidebar/sidebar.component.spec.ts
- src/app/shared/components/table/table.component.spec.ts
BRS-965
Various shared component tests. Trying to isolate the tests from DUP specific mock data so the tests can be reused in future shareable components.
> BRS-965-6: various shared components

- src/app/shared/components/table/table-components/table-button/table-button.component.spec.ts
- src/app/shared/components/table/table-row/table-row.component.html
- src/app/shared/components/table/table-row/table-row.component.spec.ts
- src/app/shared/components/table/table.component.spec.ts
BRS-965
Improving test coverage for shared table components.
> BRS-965-7: shared table components

- src/app/services/loading.service.spec.ts
- src/app/services/logger.service.spec.ts
- src/app/services/modifier.service.spec.ts
- src/app/services/modifier.service.ts
- src/app/services/park.service.spec.ts
- src/app/services/pass.service.spec.ts
- src/app/services/pass.service.ts
- src/app/services/reservation.service.spec.ts
- src/app/shared/utils/mock-data.ts
BRS-965
A handful more services checked off the coverage list. Coverage @79.88%
> BRS-965 various serivces: loading, logging, modifier, park, pass, reservation

- src/app/home/home.component.spec.ts
- src/app/resolvers/facility-add.resolver.spec.ts
- src/app/resolvers/facility-details.resolver.spec.ts
- src/app/resolvers/facility.resolver.spec.ts
- src/app/resolvers/park.resolver.spec.ts
- src/app/shared/components/ds-forms/base-form/base-form.component.spec.ts
BRS-965
Resolver coverage. Also removing `base-form` race condition test.
> BRS-965: resolver coverage

- src/app/shared/utils/utils.spec.ts
BRS-965
Coverage for utils. Unable to cover 100% due to some util functions being reliant on system timezone, which cannot be ascertained at runtime.
> BRS-965: utils coverage

- src/app/shared/components/breadcrumb/breadcrumb.component.spec.ts
BRS-965
Copying breadcrumb coverage from https://github.com/bcgov/bcparks-ar-admin/pull/191. Coverage at 82.6$
> BRS-965: shared breadcrumb component

- src/app/parks-management/park-edit-form/park-edit-form.component.html
BRS-924
https://bcparksdigital.atlassian.net/browse/BRS-924
Add missing text from park edit page - Jess's First PR!
> BRS-924: Missing text on park edit page

- src/app/pass-management/manual-entry/manual-entry.component.html
- src/app/pass-management/manual-entry/manual-entry.component.ts
- src/app/pass-management/pass-lookup/pass-lookup.component.html
- src/app/pass-management/pass-lookup/pass-lookup.component.ts
- src/app/pass-management/pass-management.component.html
- src/app/pass-management/pass-management.component.spec.ts
- src/app/pass-management/pass-management.component.ts
- src/app/pass-management/pass-management.module.ts
- src/app/shared/components/qr-scanner/qr-scanner.component.html
- src/app/shared/components/qr-scanner/qr-scanner.component.ts
BRS-999
https://bcparksdigital.atlassian.net/browse/BRS-999
- Adding the ability to use external camera apps to scan QR.
- Setting QR scanner to "try harder" mode
- Stubbing out manual lookup
> BRS-999: various updates to QR

- src/app/guards/auth.guard.ts
- src/app/services/keycloak.service.ts
- src/env.js
BRS-1026
https://bcparksdigital.atlassian.net/browse/BRS-1026
Handle login redirect after auth with IDIR using localStorage.
> BRS-1026: Preserve redirect URL on initial login in localStorage

- src/app/parks-management/facility-details/passes-filter/passes-filter.component.ts
- src/app/parks-management/facility-edit/facility-edit-form/facility-edit-form.component.ts
- src/app/parks-management/modifiers-form/modifiers-form.component.ts
- src/app/parks-management/park-edit-form/park-edit-form.component.html
- src/app/parks-management/park-edit-form/park-edit-form.component.ts
- src/app/shared/components/ds-forms/base-form/base-form.component.spec.ts
- src/app/shared/components/ds-forms/base-form/base-form.component.ts
BRS-1046
https://bcparksdigital.atlassian.net/browse/BRS-1046
Some of the changes introduced in BRS-1046 necessitate an update of our common form control components. This was used as an opportunity to improve the disabled field logic of the common form component.
> BRS-1046 common form disable field logic rewrite

- src/app/pass-management/manual-entry/manual-entry.component.html
- src/app/pass-management/manual-entry/manual-entry.component.scss
- src/app/pass-management/pass-check-in-list/pass-check-in-list.component.ts
- src/app/pass-management/pass-management.component.html
- src/app/pass-management/pass-management.component.scss
- src/app/shared/components/qr-scanner/qr-scanner.component.html
- src/app/shared/components/qr-scanner/qr-scanner.component.scss
BRS-999
https://bcparksdigital.atlassian.net/browse/BRS-999
Cleaning up UI.
> BRS-999: Cleaning up UI

- src/app/pass-management/pass-management.component.ts
BRS-1053
https://bcparksdigital.atlassian.net/browse/BRS-1053
Error catching for failed scans.
> BRS-1053: Error catching for failed scans

- src/app/pass-management/pass-check-in-list/pass-check-in-list.component.html
- src/app/pass-management/pass-check-in-list/pass-check-in-list.component.ts
BRS-999
https://bcparksdigital.atlassian.net/browse/BRS-999
Fixing issues with manual lookup list.
> BRS-999: Fixing issues with manual lookup list

- .vscode/settings.json
- src/app/parks-management/facility-details/passes-list/passes-list.component.spec.ts
- src/app/pass-management/manual-entry/manual-entry.component.spec.ts
- src/app/pass-management/pass-check-in-list/pass-check-in-list.component.spec.ts
- src/app/pass-management/pass-check-in-list/pass-check-in-list.component.ts
- src/app/pass-management/pass-management.component.spec.ts
- src/app/pass-management/qr-result/qr-result.component.spec.ts
- src/app/services/pass.service.spec.ts
- src/app/services/pass.service.ts
- src/app/shared/components/qr-scanner/qr-scanner.component.spec.ts
- src/app/shared/components/qr-scanner/qr-scanner.service.spec.ts
BRS-1055
https://bcparksdigital.atlassian.net/browse/BRS-1055
Unit tests for pass management.
> BRS-1055: Unit tests for pass management

- src/app/parks-management/facility-details/passes-list/passes-list.component.spec.ts
BRS-1055
https://bcparksdigital.atlassian.net/browse/BRS-1055
Altering `spec` for `passes-list` component to remove improperly injected service.
> BRS-1055-2: fix to passes-list test

- src/app/services/keycloak.service.spec.ts
- src/app/services/keycloak.service.ts
BRS-1044
https://bcparksdigital.atlassian.net/browse/BRS-1044
This updates the login guard for admin so that the user will have their last login idp working.
> BRS-1044: Updating login checker.

- src/app/parks-management/facility-details/facility-details.component.html
- src/app/parks-management/facility-details/facility-details.component.spec.ts
- src/app/parks-management/facility-edit/facility-edit-form/facility-edit-form-publishing-details/facility-edit-form-publishing-details.component.html
- src/app/parks-management/facility-edit/facility-edit-form/facility-edit-form-publishing-details/facility-edit-form-publishing-details.component.ts
- src/app/parks-management/facility-edit/facility-edit-form/facility-edit-form.component.html
- src/app/parks-management/facility-edit/facility-edit-form/facility-edit-form.component.ts
- src/app/parks-management/park-details/park-details.component.ts
- src/app/parks-management/parks-management.module.ts
- src/app/shared/components/text-with-icons/text-with-icons.component.html
- src/app/shared/components/text-with-icons/text-with-icons.component.scss
- src/app/shared/components/text-with-icons/text-with-icons.component.spec.ts
- src/app/shared/components/text-with-icons/text-with-icons.component.ts
- src/app/shared/components/text-with-icons/text-with-icons.module.ts
- src/app/shared/utils/mock-data.ts
BRS-1044
https://bcparksdigital.atlassian.net/browse/BRS-1044
Turning off/on QR codes per facility, adds qr code visualization in various areas.  Requires PR #239 in api repo.
> BRS-1044: Turning off/on QR codes per facility, adds qr code visualization in various areas.  Requires PR #239 in api repo.

- .github/workflows/deploy-dev.yaml
- .github/workflows/on-pr.yaml
BRS-1051
Revising dev workflow.
> BRS-1051: Revising dev workflow

- .github/workflows/deploy-dev.yaml
- .github/workflows/on-pr.yaml
BRS-1051
Updating on-pr and dev workflow.
> BRS-1051: Updating on-pr and dev workflow

- .github/workflows/on-pr.yaml
BRS-1051
Updating cache id for on PR build.
> BRS-1051: updating cache id for on PR build

- .github/workflows/deploy-dev.yaml
- .github/workflows/on-pr.yaml
BRS-1051
Changing build cache key to event number.
> BRS-1051: Changing build cache key to event number.

- .github/workflows/deploy-dev.yaml
- .github/workflows/deploy-prod.yaml
- .github/workflows/deploy-test.yaml
BRS-1051
Updating test and prod workflows.
> BRS-1051: Updating test and prod workflows

- src/app/parks-management/facility-details/facility-details.component.html
BRS-1044
https://bcparksdigital.atlassian.net/browse/BRS-1044
Fix for missing optional - facility details page was throwing errors.
> BRS-1044: Fix for missing optional.

- src/app/pass-management/pass-management.component.ts
BRS-1062
https://bcparksdigital.atlassian.net/browse/BRS-1062
Enable camera after clicking camera in button group.
> BRS-1062: Enable camera after clicking camera in button group

- src/app/parks-management/park-details/park-details.component.spec.ts
- src/app/parks-management/park-details/park-details.component.ts
BRS-1075
https://bcparksdigital.atlassian.net/browse/BRS-1075
Facility list was not listening to autofetcher properly - most recently loaded facility list was being displayed.
> BRS-1075: correct facilities on autorefresh

- src/app/pass-management/pass-management.component.ts
BRS-1067
https://bcparksdigital.atlassian.net/browse/BRS-1067
Fixing invalid QR error spam.
> BRS-1067: fixing invalid QR error spam

- src/app/parks-management/facility-edit/facility-edit-form/facility-edit-form.component.ts
- src/app/services/facility.service.ts
BRS-1072
https://bcparksdigital.atlassian.net/browse/BRS-1072
This fixes the create facility create logic, and updates the cache accordingly.
> BRS-1072: Console error when creating a new Facility

- src/app/services/api.service.ts
- src/app/services/auto-fetch.service.ts
- src/app/services/park.service.ts
This adds a bit of robustness to the error handling.
> NOBUG: Update error handling.

- src/app/shared/components/qr-scanner/qr-scanner.component.html
- src/app/shared/components/qr-scanner/qr-scanner.component.scss
> NOBUG: Spacing fix

- src/app/metrics/metrics-filter/metrics-filter.component.spec.ts
- src/app/metrics/metrics-filter/metrics-filter.component.ts
- src/app/metrics/site-metrics/site-metrics.component.spec.ts
- src/app/metrics/site-metrics/site-metrics.component.ts
- src/app/shared/utils/mock-data.ts
BRS-1087
https://bcparksdigital.atlassian.net/browse/BRS-1087
Add unit tests for components site-metrics and metrics-filter. Some tests for metrics-filter may need to wait for integration ticket.
> BRS-1087: Add unit tests for components site-metrics and metrics-filter

- src/app/metrics/site-metrics/site-metrics.component.html
BRS-1101
https://bcparksdigital.atlassian.net/browse/BRS-1101
minor UI updates to metrics page
> BRS-1101: minor UI updates to metrics page

- src/app/metrics/site-metrics/site-metrics.component.html
- src/app/metrics/site-metrics/site-metrics.component.ts
BRS-1082
https://bcparksdigital.atlassian.net/browse/BRS-1082
Buttons currently set to display: none until download functionality can be added. This ticket is for the UI only.
> BRS-1082: download buttons added to graph cards

- src/app/metrics/metrics-filter/metrics-filter.component.ts
- src/app/metrics/site-metrics/site-metrics.component.html
- src/app/metrics/site-metrics/site-metrics.component.spec.ts
- src/app/metrics/site-metrics/site-metrics.component.ts
- src/app/services/metrics.service.spec.ts
- src/app/services/metrics.service.ts
- src/app/shared/utils/utils.spec.ts
- src/app/shared/utils/utils.ts
BRS-1083
https://bcparksdigital.atlassian.net/browse/BRS-1083
Adding ability to download .csv of capacity metrics graph when a single facility is selected. Removal of old metrics endpoint will be handled as part of BRS-1049 as the old endpoint services that particular report generation (pass statuses).
> BRS-1083: adding capacity report csv download to metrics

- src/app/metrics/metrics-filter/metrics-filter.component.html
NOBUG
https://bcparksdigital.atlassian.net/browse/BRS-1020
Removing Download Reports accordion visible on mobile view - we dont use this button anymore.
> NOBUG removing unused download reports button on mobile

- package.json
- yarn.lock
This updates keycloak-js to the latest working version. The very latest is a broken package on npm.
> NOBUG: Security updates for keycloak-js.

- src/app/login/login.component.html
BRS-977
https://bcparksdigital.atlassian.net/browse/BRS-977
> BRS-977 updating BCeID link

- package.json
- yarn.lock
BRS-1159
https://bcparksdigital.atlassian.net/browse/BRS-1159
Bumped version of BC Parks Bootstrap theme.
> BRS-1159: Bumped version of BC Parks Bootstrap theme

- src/app/home/home.component.spec.ts
- src/app/home/home.component.ts
BRS-1162
https://bcparksdigital.atlassian.net/browse/BRS-1162
This updates the copy text as well as improve the quality of unit tests.
> BRS-1162: Updated copy text and improve unit tests.

- src/app/pass-management/pass-search/pass-search.component.ts
- src/app/pass-management/pass-search/passes-list/passes-list.component.ts
> NOBUG: Updating interfaces to reflect linter complaints.

- src/app/pass-management/pass-search/passes-filter/passes-filter.component.html
- src/app/pass-management/pass-search/passes-list/passes-list.component.ts
- src/app/shared/components/ds-forms/shortdate-picker/shortdate-picker.component.ts
BRS-1164
https://bcparksdigital.atlassian.net/browse/BRS-1164
Minor UI updates.
> BRS-1164 pass search UI changes

- src/app/parks-management/facility-edit/facility-edit.component.spec.ts
- src/app/parks-management/facility-edit/facility-edit.component.ts
BRS-1169
https://bcparksdigital.atlassian.net/browse/BRS-1169
Fixing modifier table.
> BRS-1169: fixing modifier table

- src/app/pass-management/pass-check-in-list/pass-check-in-list.component.html
This updates the confirmation page to show the number of guests.
> NOBUG: Hotfix to show number of guests.

- src/app/parks-management/modifiers-form/modifiers-form.component.ts
BRS-1201
https://bcparksdigital.atlassian.net/browse/BRS-1201
Bug fix for capacity modifiers
> BRS-1201: fixed form reset after save

- CODEOFCONDUCT.md
- README.md
BRS-1204
https://bcparksdigital.atlassian.net/browse/BRS-123
This is a description.
> BRS-1204: changed README.md

- src/app/metrics/site-metrics/site-metrics.component.html
- src/app/shared/components/ds-forms/shortdate-picker/shortdate-picker.component.html
Changed two text fields on site metrics for DUP Admin. Tested on local environment.
> BRS-1127: Updated text bugs on site metrics page (#286)

- README.md
Added "Local Development" Section
Under that added
"## Development Server
```
yarn install
yarn start
```
Navigate to http://localhost:4200/. The application will automatically reload if you change any of the source files."
Add "Running unit tests" section with text
"yarn test-ci --  to run all tests. 
yarn test-ci -- --include src/app/shared/components/metrics to run on a specific file
> Update more technical parts of README.md

- src/app/metrics/metrics-filter/metrics-filter.component.ts
No change to disabled dropdown display
BRS-1127
https://bcparksdigital.atlassian.net/browse/BRS-1127
Part of number 9 from 1127
> BRS-1127: default for a specific park is all facilities. 

- .github/workflows/deploy-dev.yaml
- .github/workflows/deploy-prod.yaml
- .github/workflows/deploy-test.yaml
- README.md
BRS-1152
https://bcparksdigital.atlassian.net/browse/BRS-1152
Documentation and updated env setting.
> BRS-1152: Documentation and updated env setting.

- src/app/services/auto-fetch.service.ts
BRS-1223
https://bcparksdigital.atlassian.net/browse/BRS-1223
This updates the utility function that checks for updates (or lack thereof) inside the autofetcher.
> BRS-1223: DUP-> Inconsistent search behaviour on Pass Search page

- src/app/services/metrics.service.ts
BRS-1128
https://bcparksdigital.atlassian.net/browse/BRS-1228
> BRS-1228 adding checkedIn status to csv export

- src/app/pass-management/pass-search/passes-filter/passes-filter.component.ts
BRS-1246
https://bcparksdigital.atlassian.net/browse/BRS-1246
Front end incorrectly passing 'null' as a string for passStatus queryParam.
> BRS-1246 pass filter status by 'all'

- .github/workflows/deploy-dev.yaml
- .github/workflows/deploy-prod.yaml
- .github/workflows/deploy-test.yaml
- .github/workflows/on-pr.yaml
NOBUG
Updating to node 18. Fix missing cache issue.
> NOBUG: Updating to node 18. Fix missing cache issue.

- .github/workflows/deploy-dev.yaml
- .github/workflows/deploy-prod.yaml
- .github/workflows/deploy-test.yaml
NOBUG
Updating aws action for creds.
> NOBUG: Updating aws action for creds

- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/faq/faq-edit/faq-edit.component.html
- src/app/faq/faq-edit/faq-edit.component.ts
- src/app/faq/faq-edit/faq.component.spec.ts
- src/app/faq/faq-routing.module.ts
- src/app/faq/faq.component.html
- src/app/faq/faq.component.scss
- src/app/faq/faq.component.spec.ts
- src/app/faq/faq.component.ts
- src/app/faq/faq.module.ts
- src/app/home/home.component.spec.ts
- src/app/home/home.component.ts
- src/app/services/faq.service.ts
BRS-325
[Ticket 325](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=47055544)
Adds FAQ to sidebar if a user is sysadmin
Allows users to access FAQ page if user is a sysadmin
On FAQ page Load retrieves FAQ data to be displayed in WYSIWYG
WYSIWYG edits contents of FAQ data stored in db
Toast notification on success or failure of editing FAQ
Buttons to match Edit park WYSIWYG
> BRS:325 - Implements FAQ for DUP admin

- src/app/services/faq.service.ts
[BRS-325](https://github.com/bcgov/parks-reso-admin/issues/325)
[BRS-325](https://github.com/bcgov/parks-reso-admin/issues/325)
Changing service to make requests to /faq instead of /readFaq and /writeFaq. To match ApiGateway config.
> Changing service to point at /faq instead of /readFaq

- src/app/guards/auth.guard.ts
- src/app/home/home.component.spec.ts
- src/app/home/home.component.ts
- src/app/services/keycloak.service.ts
Fixes: BRS-335
[BRS-335](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=51220690)
- Restricts access to admin FAQ page.
- If a unauthorized user attempts to access FAQ page through any means they will be redirected to the home page
> BRS-335:Restrict access to FAQ portal 

- src/app/services/faq.service.ts
BRS-336
[BRS-336](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=51221135)
Update toast message for success and failure of updating FAQ
> Update toast message

- src/app/home/home.component.spec.ts
- src/app/home/home.component.ts
- src/app/services/sidebar.service.ts
BRS-335
[BRS335](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=51220690)
Removed visibility of FAQ links when user does not have proper role to access.
> BRS-335fix:Removing links to FAQ when user does not have access

- src/app/parks-management/park-edit-form/park-edit-form.component.html
- src/app/parks-management/park-edit-form/park-edit-form.component.spec.ts
- src/app/parks-management/park-edit-form/park-edit-form.component.ts
[BRS-346](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=57770812)
[BRS-346](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=57770812)
Admin can toggle special closure at park level. 
Admin can add special closure text at park level.
> BRS-346:Admin ability to edit special closure status and text

- src/app/parks-management/facility-edit/facility-edit-form/facility-edit-form-publishing-details/facility-edit-form-publishing-details.component.html
Ticket: [366](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=75938748)
Notes: Changed the padding from side to top to fall in line with the other components on the same row.
> BRS-366: UI Alignment fix

- .github/workflows/deploy-dev.yaml
- .github/workflows/deploy-prod.yaml
- .github/workflows/deploy-test.yaml
Workflow fixes for Sam deployments
> Workflow Fixes

- template.yaml
Change formatting on template.yaml
> Work flow fixes

- src/app/footer/footer.component.html
- src/app/footer/footer.component.scss
Ticket: [492](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=91284780&issue=bcgov%7Cparks-reso-public%7C492)
Notes: Added land acknowledgement to the footer
> BRS-492: Land acknowledgement added to footer
