bcgov/parks-reso-admin

src/app/passes/pass-list/pass-table-row/pass-table-row.component.html
BRS-166
https://bcparksdigital.atlassian.net/browse/BRS-166
This changes fixes a bug where the cancel button was disabled when trying to cancel passes in any facility. The bug was due to the front checking whether the current status of `passStatus === 'active'`, and disabling the button if this was not true. There is an additional status `'reserved'` that should also not disable the button. Front end logic was altered to reflect this.
=> BRS-166: fixing incorrectly disabled cancel button

src/app/shared/form-generator/form-generator.component.ts, src/app/shared/utils/utils.ts
BRS-658
https://bcparksdigital.atlassian.net/browse/BRS-658
This change alters how the admin portal generates the `date` queryParam for `readPass` - since the new `readPass` as of https://github.com/bcgov/parks-reso-api/pull/108 can no longer accept the JS ISO Date long format (`Sat Jun 11 2022 00:00:00 GMT-0700 (Pacific Daylight Time)`, for example).
=> BRS-658 formatting dates as ISO to conform to new TZ changes

src/app/services/keycloak.service.ts
BRS-687
https://bcparksdigital.atlassian.net/browse/BRS-687
This redirects the user to the login page once an authRefreshError happens in keycloak, typically when the users' session expires.
=> BRS-687: Redirect to login page on authRefreshError

src/app/models/facility.ts
BRS-768
https://bcparksdigital.atlassian.net/browse/BRS-768
This update goes along with the change to the API where weekdays are defined by their name (weekdayLong) as opposed to their index (number) since luxon conflicts with jsDate.
=> BRS-768-2 changing weekday (1-indexed) to weekdayLong

src/app/parks-management/facility-edit/facility-edit-form/facility-edit-form.component.ts, src/app/parks-management/modifiers-form/modifiers-form.component.ts
NOBUG
Capacities and modifiers were being saved as strings, which led to string concatenation instead of math logic when comparing numbers. 
Note: This may fix BRS-918.
=> NOBUG: capacities saved as integers

src/app/parks-management/facility-details/passes-list/passes-list.component.html, src/app/parks-management/facility-details/passes-list/passes-list.component.ts, src/app/services/data.service.ts, src/app/services/pass.service.ts, src/app/shared/components/table/table.component.html, src/app/shared/components/table/table.component.ts, src/app/shared/utils/constants.ts
NOBUG
DUP V1 had a 'load more' feature when the number of passes returned by the pass query exceeded DynamoDB's data limit. This change builds in a 'load more' feature to the shared table component and also leverages DynamoDB's `LastEvaluatedKey` functionality. The `dataService` has two new functions: `mergeItemValue` and `appendItemValue`, for adding data to existing `dataService` objects and arrays respectively without overwriting.
=> NOBUG: Infinite pass loading

src/app/shared/utils/utils.ts
BRS-936
https://bcparksdigital.atlassian.net/browse/BRS-936
Our common form component `shortdate-picker` is applying a timezone offset to calendar dates if the browser is in a timezone other than PT. With `shortdate-picker` we only care about the calendar date. So whatever calendar date is picked in the browser, should be the same date sent to the backend, no TZ conversions necessary.
This change introduces a new function so both cases (timezone respected & timezone not respected) are handled. Also some clarification comments were added to the other datetime utils.
=> BRS-936: shortdate-picker should not account for timezone

src/app/shared/components/table/table.component.html
This change hides table rows if the system is loading data.
This was originally in the code base, but was erroneously removed when infinite loading was introduced so that the user could see existing table data while more was being brought in.
Since table data is typically cached in browser memory, when navigating from one facility to another, the table data of the previous facility persists for a few seconds while the correct data loads. This leads to a poor user experience when there is a slow connection.
In the future, we can look at a more detailed loading service so that we dont have to blanket hide data when any part of the application is loading.
=> NOBUG: hide table data if loading

src/app/parks-management/facility-edit/facility-edit-form/facility-edit-form-details/facility-edit-form-details.component.html, src/app/parks-management/facility-edit/facility-edit-form/facility-edit-form-details/facility-edit-form-details.component.ts, src/app/parks-management/facility-edit/facility-edit-form/facility-edit-form.component.html, src/app/parks-management/facility-edit/facility-edit-form/facility-edit-form.component.ts, src/app/shared/components/ds-forms/base-form/base-form.component.ts, src/app/shared/components/ds-forms/timepicker/timepicker.component.spec.ts, src/app/shared/components/ds-forms/timepicker/timepicker.component.ts
BRS-941
https://bcparksdigital.atlassian.net/browse/BRS-1941
Facility edit form `timepicker` was not resetting with the rest of the form. This is because the bound model for `timepicker` is decoupled from the form control value for the time selected. This is one of the drawbacks from using an external `timepicker` package with our latest form engine. As a workaround, an EventEmitter was added when the form is reset, and the `timepicker` listens to the event. We can expand our form engine to fire other events if necessary in the future. 
Also added test coverage for the timepicker component.
=> BRS-941: timepicker resets with rest of form

src/app/services/api.service.spec.ts, src/app/services/auto-fetch.service.spec.ts, src/app/services/data.service.spec.ts, src/app/services/event.service.spec.ts
BRS-965
Starting on DUP admin service coverage. Includes `api.service`, `auto-fetch.service`, `data.service`, and `event.service`. Total coverage at 66.6%.
=> BRS-965: api & data service test coverage

src/app/shared/components/ds-forms/base-form/base-form.component.spec.ts
BRS-965
Final attempt to solve the `baseform` race condition issue with UTs. The intention was to delete the test altogether but the failure logs get overwritten when the GH actions for 'Testing' is re-run. Next time a race condition occurs, we should pinpoint the spot in the tests where it is failing.
=> BRS-965: baseform race condition 2

src/app/guards/auth.guard.spec.ts, src/app/services/auto-fetch.service.spec.ts, src/app/shared/components/metrics/basic-metric/basic-metric.component.html, src/app/shared/components/metrics/basic-metric/basic-metric.component.spec.ts, src/app/shared/components/metrics/basic-metric/basic-metric.component.ts, src/app/shared/components/metrics/shared-metrics.module.ts, src/app/shared/utils/count-to.directive.spec.ts, src/app/shared/utils/count-to.directive.ts, src/app/shared/utils/utils.spec.ts
BRS-1032
https://bcparksdigital.atlassian.net/browse/BRS-1032
This change adds a basic metrics card component that can be called to render a basic numerical metric. This can be done in inline HTML by the following:
```
basic:
<app-basic-metric [label]="'Metric Label'" [value]="numericVariable"></app-basic-metric>
with ticker animation:
<app-basic-metric [label]="'Metric Label'" [value]="numericVariable" [animate]="true"></app-basic-metric>
```
You can control the ticker animation with the following directives:
`[animationDuration]="1500"` set ticker animation duration (1.5s by default)
`[animationJitter]="true"` apply duration jitter to animations (animations take up to 20% longer to eliminate the appearance of synchronization between multiple metrics cards).
A handful of UT bugs were …
=> BRS-1032 basic metrics card stubout

src/app/shared/components/metrics/basic-metric/basic-metric.component.html, src/app/shared/components/metrics/basic-metric/basic-metric.component.spec.ts, src/app/shared/components/metrics/basic-metric/basic-metric.component.ts, src/app/shared/components/metrics/chart-metric/chart-metric.component.html, src/app/shared/components/metrics/chart-metric/chart-metric.component.spec.ts, src/app/shared/components/metrics/chart-metric/chart-metric.component.ts, src/app/shared/components/metrics/metric-card/metric-card.component.html, src/app/shared/components/metrics/metric-card/metric-card.component.spec.ts, src/app/shared/components/metrics/metric-card/metric-card.component.ts, src/app/shared/components/metrics/shared-metrics.module.ts
BRS-300
https://bcparksdigital.atlassian.net/browse/BRS-300
Existing metrics components build as part of BRS-300 (BRS-1032, -1033, -1034 etc) were built with the metrics card border and title build individually into each component. This change breaks out the card so it can be reused across all metrics components, and the metrics contents are nested within using `<ng-content>`
=> BRS-300-1: decouple metrics cards from their contents

src/app/guards/auth.guard.ts, src/app/services/keycloak.service.ts
This fixes an issue where the last IDP was being stored incorrectly. It should be fired/stored upon a successful IDP login, not some other random place.
=> NOBUG: Fixing keycloak storage mechanism for last idp logged in.

src/app/metrics/metrics-filter/metrics-filter.component.html, src/app/metrics/metrics-filter/metrics-filter.component.spec.ts, src/app/metrics/metrics-filter/metrics-filter.component.ts, src/app/metrics/site-metrics/site-metrics.component.html, src/app/metrics/site-metrics/site-metrics.component.scss, src/app/metrics/site-metrics/site-metrics.component.spec.ts, src/app/metrics/site-metrics/site-metrics.component.ts, src/app/resolvers/metrics.resolver.spec.ts, src/app/resolvers/metrics.resolver.ts, src/app/services/metrics.service.spec.ts, src/app/services/metrics.service.ts, src/app/shared/components/ds-forms/base-form/base-form.component.ts, src/app/shared/components/ds-forms/base-input/base-input.component.ts, src/app/shared/components/ds-forms/picklist/picklist.component.html, src/app/shared/components/ds-forms/picklist/picklist.component.ts, src/app/shared/components/ds-forms/shortdate-picker/shortdate-picker.component.html, src/app/shared/components/ds-forms/shortdate-picker/shortdate-picker.component.ts, src/app/shared/components/metrics/chart-metric/chart-metric-plugins.ts, src/app/shared/components/metrics/chart-metric/chart-metric.component.spec.ts, src/app/shared/components/metrics/chart-metric/chart-metric.component.ts, src/app/shared/utils/constants.ts, src/app/shared/utils/count-to.directive.ts, src/app/shared/utils/mock-data.ts
BRS-1020
https://bcparksdigital.atlassian.net/browse/BRS-1020
Requires https://github.com/bcgov/parks-reso-api/pull/252.
There are now two very similar instances of metrics related services in the codebase:
- Instances of `metric` refer to implementations for the OLD metrics services & systems.
- Instances of `metrics` <- NOTE THE plural 's' refer to implementations of the NEW metrics system. 
References to the old implementations remain in the code base as their functionality is important for future tickets (BRS-1049) but should be phased out in a future ticket. 
Front end changes to go along with the new API changes for continuous metrics monitoring. Statistics for this iteration include Pass Breakdown by Status and Pass Activity by Day. Date range length is limited to a 1 year period …
=> BRS-1020: New Metrics FE changes

src/app/services/keycloak.service.ts
This pushed the browser into the login page once an error happens in the KC service.
=> NOBUG: Redirect on errors.

src/app/pass-management/pass-check-in-list/pass-check-in-list.component.spec.ts, src/app/pass-management/pass-management-home/pass-management-home.component.html, src/app/pass-management/pass-management.module.ts, src/app/pass-management/pass-search/pass-search.component.html, src/app/pass-management/pass-search/pass-search.component.spec.ts, src/app/pass-management/pass-search/pass-search.component.ts, src/app/pass-management/pass-search/passes-capacity-bar/passes-capacity-bar.component.html, src/app/pass-management/pass-search/passes-capacity-bar/passes-capacity-bar.component.scss, src/app/pass-management/pass-search/passes-filter/passes-filter.component.ts, src/app/pass-management/pass-search/passes-list/pass-accordion/pass-accordion.component.html, src/app/pass-management/pass-search/passes-list/pass-accordion/pass-accordion.component.scss, src/app/pass-management/pass-search/passes-list/pass-accordion/pass-accordion.component.spec.ts, src/app/pass-management/pass-search/passes-list/pass-accordion/pass-accordion.component.ts, src/app/pass-management/pass-search/passes-list/passes-list.component.html, src/app/pass-management/pass-search/passes-list/passes-list.component.spec.ts, src/app/pass-management/pass-search/passes-list/passes-list.component.ts, src/app/pass-management/pass-search/passes-utility-buttons/passes-utility-buttons.component.spec.ts, src/app/pass-management/pass-search/passes-utility-buttons/passes-utility-buttons.component.ts, src/app/services/data.service.ts, src/app/services/reservation.service.spec.ts, src/app/services/reservation.service.ts, src/app/shared/utils/constants.ts, src/app/shared/utils/mock-data.ts
BRS-1089/BRS-1017
https://bcparksdigital.atlassian.net/browse/BRS-1089
https://bcparksdigital.atlassian.net/browse/BRS-1017
This change introduces new visual updates to the Pass Management section of the site, now located on its own route. The updates include:
- new accordion-style table display for passes returned by the pass search filters
- responsive table columns that collapse into the accordion dropdown based on importance
- various pass data elements added to the pass results
- Filter returned passes based on `checkedIn` status
A couple of points:
1.  The new accordions are complex and, on slower browsers, may slow down pages with many results ( >1000, for example, if you don't filter by a date).
2. The responsive design does not include html table elements (`tr`, `td`, `tbody`, …
=> BRS-1089 & BRS-1017: updates to pass list

src/app/services/auto-fetch.service.ts
BRS-1166
https://bcparksdigital.atlassian.net/browse/BRS-1166
This solves an issue where the filters are getting force updated from the auto-fetcher service even if there were no changes to park and facility list data.  This will deal with 99% of the cases where there are no changes.  When there are changes, it will reset the UI but that is to be expected because we won't want the user to be able to send queries to say, non-existing facilities anymore, therefore the dropdowns should change.
=> BRS-1166: Avoiding filter changes when data in backend does not change.

src/app/parks-management/park-details/park-details.component.html, src/app/parks-management/park-edit-form/park-edit-form.component.html, src/app/parks-management/park-edit-form/park-edit-form.component.spec.ts, src/app/parks-management/park-edit-form/park-edit-form.component.ts
Jira Ticket:
BRS-267 - Add safety video to Park Information
Links to DUP-PUBLIC PR: https://github.com/bcgov/parks-reso-public/pull/271
Links to DUP-API PR: https://github.com/bcgov/parks-reso-api/pull/298
Jira Ticket URL:
https://github.com/orgs/bcgov/projects/49/views/2?pane=issue&itemId=39881272
Description:
Add section to edit form to include video link for park.
Summary page now includes the Link for park preview.
Logic included to add video link to the PUT request when editing a park.
=> BRS-267: Adding fields to supply safety video link through edit park

src/app/parks-management/park-edit-form/park-edit-form.component.ts
BRS-311 
Links to [DUP - API - #312 ](https://github.com/bcgov/parks-reso-api/pull/312)
[DUP Admin -> The "Park name" should be read only in edit mode.#311](https://github.com/orgs/bcgov/projects/49/views/2?pane=issue&itemId=42084240)
Disable the Park Name field on edit park form.
=> BRS-311: Disable edit park name through DUP Admin

src/app/app-routing.module.ts, src/app/shared/components/sidebar/sidebar.component.spec.ts, src/app/shared/components/sidebar/sidebar.component.ts
Added a `sidebar: <true/false>` in order to allow the sidebar to reference whether or not to show the route.  Some routes were not useful to be in the sidebar.
=> 308: DUP Admin - empty links in menu

src/app/services/metrics.service.ts
With [#341](https://github.com/bcgov/parks-reso-api/pull/341), completes #309.
Adds the new fields of `status` and `passesRequired` to the metrics csv report. Note: [#341](https://github.com/bcgov/parks-reso-api/pull/341) must first be merged.
=> PDR-309 adding status and passes required to metrics csv

src/app/shared/components/ds-forms/wysiwyg-input/wysiwyg-input.component.html
Ticket: [405](https://github.com/orgs/bcgov/projects/49/views/1?pane=issue&itemId=67019537&issue=bcgov%7Cparks-reso-public%7C405)
Notes: Added the link feature to the WYSIWYG text box. This will allow DUP admins to edit links and select how they will be opened from within the admin portal.
=> BRS-405: Add ability to edit link in WYSIWYG

package.json, yarn.lock
Temporarily resolves https://github.com/bcgov/parks-data-register/issues/564. 
Upgrades to `keycloak-js@25.0.6` instead of the recommended `keycloak-js@26.2.0`. Will need to bump the angular version before upgrading to the recommended version.
=> DUP-564: bumping keycloak-js version as temporary fix
